#!/bin/bash

mkdir -p /var/run/rrdcached
chown librenms:librenms /var/run/rrdcached

rrdcached -g -s librenms -l unix:/var/run/rrdcached/rrdcached.sock -j /var/lib/rrdcached/journal/ -F -b /opt/librenms/rrd/ -B -w 1800 -z 1800 -f 3600 -t 4

